workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

variables:
  TF_ROOT: ${CI_PROJECT_DIR}
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_PROJECT_NAME}
  TF_VAR_REMOTE_STATE_PASSWORD: ${CI_JOB_TOKEN}

cache:
  key: production
  paths:
    - ${TF_ROOT}/.terraform
    - ${TF_ROOT}/.terraform.lock.hcl

before_script:
  - cd ${TF_ROOT}

stages:
  - validate
  - plan
  - apply
  - trigger-app


validate:
  stage: validate
  script:
    - gitlab-terraform validate

plan:
  stage: plan
  script:
    - apk update
    - apk add aws-cli
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

apply:
  stage: apply
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
      when: manual
  script:
    - |
      apk update
      apk add aws-cli
      curl -LO https://storage.googleapis.com/kubernetes-release/release/v${TF_VAR_EKS_VERSION}.0/bin/linux/amd64/kubectl
      chmod +x ./kubectl
      mv ./kubectl /usr/local/bin/kubectl
    - gitlab-terraform apply
    - aws eks update-kubeconfig --name $TF_VAR_EKS_CLUSTER_NAME
    - kubectl patch configmap/aws-auth -n kube-system --patch "$(cat $EKS_ADMIN_USERS_CM_PATCH)"
  dependencies:
    - plan
  environment:
    name: production
    on_stop: desctroy

desctroy:
  stage: apply
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
      when: manual
      allow_failure: true
  script:
    - gitlab-terraform destroy
  environment:
    name: production
    action: stop


Trigger App1 Deploy:
  stage: trigger-app
  rules:
  - if: $CI_COMMIT_REF_NAME == "master"
    when: manual
  trigger: 
    project: devops/aws-terraform/applications/app1

Trigger App2 Deploy:
  stage: trigger-app
  rules:
  - if: $CI_COMMIT_REF_NAME == "master"
    when: manual
  trigger: 
    project: devops/aws-terraform/applications/app2

Trigger App3 Deploy:
  stage: trigger-app
  rules:
  - if: $CI_COMMIT_REF_NAME == "master"
    when: manual
  trigger: 
    project: devops/aws-terraform/applications/app3
